// ==========================================
// BUNU BİLİYOR MUYDUNUZ - 200 BİLGİ
// ==========================================

const BILGILER = [
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "II. Dünya Savaşı sırasında Coca-Cola şurubu Almanya'ya ithal edilemeyince alternatif olarak Fanta icat edilmiştir." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Müttefikler, II. Dünya Savaşı'nda düşmanı kandırmak için şişme tanklardan oluşan 'Hayalet Ordu' adında gizli bir birlik kurmuştur." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "ABD ordusunun Soğuk Savaş yıllarında yanlışlıkla denizlere düşürdüğü ve hâlâ bulunamayan en az 6 adet kayıp nükleer bombası vardır." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "1932 yılında Avustralya ordusu, ekinlere zarar veren 20.000 devekuşuna karşı savaş ilan etmiş ve savaşı devekuşları kazanmıştır!" },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "II. Dünya Savaşı'nda Japon askerleri, ABD'ye karşı rüzgarla taşınan 9.000 adet balon bomba fırlatmıştır." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Normandiya Çıkarması'nda Müttefik askerleri, düşmanı şaşırtmak için paraşütle inen kuklalar kullanmıştır." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Kore Savaşı hâlâ resmen bitmemiştir; 1953'te ateşkes imzalanmış ancak barış antlaşması hiç yapılmamıştır." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Soğuk Savaş sırasında ABD, Ay üzerinde bir nükleer bomba patlatarak gücünü göstermeyi planlamıştır (Proje A119)." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "II. Dünya Savaşı'nda radar teknolojisi olmasaydı Britanya Savaşı kaybedilebilirdi." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Stalingrad Savaşı o kadar kanlıydı ki ortalama bir askerin yaşam süresi 24 saatten azdı." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "II. Dünya Savaşı'nda ABD, Japon şifrelerini kırmak için Navajo dilini kullanan yerli askerler görevlendirmiştir." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Hitler, Paris'i işgal ettiğinde Eyfel Kulesi'nin asansör kablolarını kestirmişti; bu yüzden Hitler kuleye tırmanamadı." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Japonya, II. Dünya Savaşı sonrasında anayasal olarak savaş açma hakkından vazgeçmiştir (9. Madde)." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "İlk atom bombası testi 'Trinity' sırasında bilim insanları patlamanın atmosferi tutuşturma riskini hesaplamıştı." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Berlin Duvarı yıkıldığında Doğu Alman askerleri kendi halkına ateş açma emri almış ancak buna uymamıştır." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Vietnam Savaşı sırasında ABD, 'Agent Orange' adlı kimyasal silahı kullanarak ormanları yok etmiştir." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Türk ordusu, Kore Savaşı'nda Kunuri Muharebesi'nde gösterdiği cesaretle dünya çapında ün kazanmıştır." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Soğuk Savaş'ta SSCB, ABD'ye karşı 'Dead Hand' (Ölü El) adında otomatik nükleer misilleme sistemi kurmuştur." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Kıbrıs Barış Harekâtı sırasında Türk askerleri paraşütle indirilmiş ve 'Ayşe Tatile Çıksın' parolasıyla harekât başlatılmıştır." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Çanakkale Savaşı'nda bir saatte 6.000'den fazla Avustralyalı ve Yeni Zelandalı asker hayatını kaybetmiştir." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "II. Dünya Savaşı'nda kadınlar ABD fabrikalarında çalışarak savaş uçakları ve gemileri üretmiştir." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Almanlar, II. Dünya Savaşı'nda Enigma şifre makinesini kullanmış; Turing ve ekibi bu şifreyi kırarak savaşı kısaltmıştır." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Pearl Harbor saldırısı öncesinde ABD, Japon saldırısını öngören istihbarat raporlarını görmezden gelmiştir." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Dresden Bombardımanı'nda sadece bir gecede 25.000'den fazla sivil hayatını kaybetmiştir." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "II. Dünya Savaşı'nda Stalin, oğlu Yakov'un Almanlara esir düşmesi üzerine onu kurtarmayı reddetmiştir." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Soğuk Savaş sırasında SSCB, ABD elçiliğine dinleme cihazı yerleştirmek için 'The Thing' adında özel bir cihaz kullanmıştır." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "II. Dünya Savaşı'nda bir milyondan fazla Yahudi, toplama kamplarında değil, sokaklarda vurularak öldürülmüştür." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Alman ordusu, işgal ettiği ülkelerde 'Volksdeutsche' adı altında etnik Almanları silahlandırmıştır." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "İngiliz casuslar, II. Dünya Savaşı'nda Almanları yanıltmak için sahte ceset kullanmıştır (Operasyon Mincemeat)." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "II. Dünya Savaşı sonrası Japonya'da kadınlar ilk kez oy kullanma hakkı elde etmiştir." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Osmanlı Devleti, I. Dünya Savaşı'na girdiğinde 90.000 askere sahipti; savaş sonunda yaklaşık 325.000 şehit verdi." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Çanakkale'de Nusret Mayın Gemisi'nin döşediği mayınlar, savaşın kaderini değiştirmiştir." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "II. Dünya Savaşı'nda bir Sovyet keskin nişancı, 300'den fazla Alman askerini öldürmüştür." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Fransa, II. Dünya Savaşı'nda sadece 6 hafta dayanabilmiştir." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Müttefikler, Normandiya Çıkarması'nı planlarken Hitler'i yanıltmak için sahte bir ordu kurmuştur." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "II. Dünya Savaşı'nda ilk kez kadınlar savaş pilotu olmuştur (SSCB'de 'Gece Cadıları')." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Almanya, V-2 roketleriyle Londra'yı bombalayan ilk balistik füze saldırısını gerçekleştirmiştir." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "II. Dünya Savaşı'nda Türkiye, savaşa girmemesine rağmen 1 milyon askerini silah altında tutmuştur." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Soğuk Savaş'ta SSCB, ABD'ye karşı uzayda ilk canlı olarak Laika adlı köpeği göndermiştir." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Hitler'in intihar ettiği sığınakta bulunan sanat eserleri günümüzde hâlâ kayıptır." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "II. Dünya Savaşı'nda Türk askerleri, İngilizler tarafından esir alınan Alman generalini teslim etmiştir." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Birleşmiş Milletler, II. Dünya Savaşı sonrası 51 ülke tarafından kurulmuştur." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Türk Kurtuluş Savaşı'nda cepheye silah taşıyan 'Kastamonu Müfrezesi' kadınlardan oluşuyordu." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "II. Dünya Savaşı'nda Naziler, Polonya'da 6 milyon kişiyi öldürmüştür." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Napolyon'un ordusu, Rusya seferinde 500.000 askerinden sadece 100.000'ini geri getirebilmiştir." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Türkiye, Kore Savaşı'na 15.000 asker göndermiş ve 741 şehit vermiştir." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "İkinci Dünya Savaşı'nda Almanlar, tank yakıtı bulamadıkları için atları kullanmıştır." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Hiroşima'ya atılan atom bombası, 140.000 kişinin ölümüne yol açmıştır." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "NATO, 1949'da 12 ülke tarafından kurulmuştur; Türkiye 1952'de katılmıştır." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Vietnam Savaşı, ABD'nin en uzun süren savaşıdır (1955-1975)." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "SSCB, 1979'da Afganistan'ı işgal etmiş ancak 10 yıl sonra yenilgiyle çekilmiştir." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "II. Dünya Savaşı'nda Türk pasaportu taşıyan Yahudiler, Holokost'tan kurtulmuştur." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Çanakkale Savaşı'nda Anzak askerleri, Türk askerlerinin cesaretine saygı duymuştur." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "II. Dünya Savaşı'nda Türk ticaret gemileri, Müttefikler tarafından batırılmıştır." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "İlk kadın savaş pilotu Sabiha Gökçen'dir ve Türk'tür." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "II. Dünya Savaşı'nda ABD, savaşan ülkelere 50 milyar dolar yardım yapmıştır." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Soğuk Savaş, 1991'de SSCB'nin dağılmasıyla resmen sona ermiştir." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Türkiye, 1950'de Kore Savaşı'na katılarak NATO üyeliğine giden yolu açmıştır." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "İkinci Dünya Savaşı sırasında Türkiye, savaş dışı kalarak 1 milyon insanını kurtarmıştır." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "II. Dünya Savaşı'nda Alman ordusunda 13 milyon asker görev yapmıştır." },
  { "kategori": "savas", "ikon": "🎖️", "bilgi": "Nürnberg Mahkemeleri, savaş suçlularının yargılandığı ilk uluslararası mahkemedir." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Atatürk, 1936'da Montrö Sözleşmesi'ni bizzat kaleme almıştır." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Türkiye'de kadınlara seçme ve seçilme hakkı 1934'te verilmiştir; Fransa'da bu hak 1944'te verilmiştir." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Kuzey Kore, 1974 yılında İsveç'ten aldığı 1.000 adet Volvo otomobilin parasını hâlâ ödememiştir." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Mustafa Kemal Atatürk, 1934'te Soyadı Kanunu'nu çıkarmış ve 'Atatürk' soyadını almıştır." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "ABD Başkanı Franklin D. Roosevelt, üst üste 4 kez başkan seçilen tek ABD başkanıdır." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Winston Churchill, 1953'te Nobel Edebiyat Ödülü kazanmıştır." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "SSCB'nin son lideri Mihail Gorbaçov, 1990'da Nobel Barış Ödülü almıştır." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Türkiye'de ilk kadın Başbakan Tansu Çiller'dir (1993)." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Fidel Castro, 1959'dan 2008'e kadar Küba'yı yönetmiştir." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Nelson Mandela, 27 yıl hapiste kaldıktan sonra Güney Afrika'nın ilk siyahi başkanı olmuştur." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "II. Elizabeth, 70 yıl tahtta kalarak Birleşik Krallık'ın en uzun süre hüküm süren hükümdarı olmuştur." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Mustafa Kemal Atatürk, Türkiye Cumhuriyeti'nin ilk cumhurbaşkanıdır ve 15 yıl görev yapmıştır." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Birleşmiş Milletler'in 5 daimi üyesinin veto hakkı vardır: ABD, Rusya, Çin, Fransa, İngiltere." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Türkiye, 1945'te BM'nin kurucu üyesi olmuştur." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Mahatma Gandhi, Hindistan'ın bağımsızlığını şiddetsiz direnişle kazanmıştır." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "John F. Kennedy, 1963'te suikaste kurban giden en genç ABD başkanıdır." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Süleyman Demirel, 7 kez Başbakanlık ve 1 kez Cumhurbaşkanlığı yapmıştır." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Angela Merkel, 16 yıl Almanya Şansölyesi olarak görev yapmıştır." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Türkiye'de 1980 darbesinden sonra 1982 Anayasası halkoyuna sunulmuştur." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Çin, 1971'de BM Güvenlik Konseyi'ndeki daimi üyeliği Tayvan'dan almıştır." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Barack Obama, ABD'nin ilk siyahi başkanıdır (2009-2017)." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Türkiye Cumhuriyeti'nin ilk kadın valisi Lale Aytaman'dır (1991)." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Avrupa Birliği, 1993'te Maastricht Antlaşması ile kurulmuştur." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Türkiye, 1999 Helsinki Zirvesi'nde AB'ye aday ülke ilan edilmiştir." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Alman Başbakanı Willy Brandt, 1970'te Varşova Gettosu anıtı önünde diz çökerek özür dilemiştir." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Rusya Devlet Başkanı Vladimir Putin, 2000'den beri iktidardadır." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Türkiye'nin ilk kadın bakanı Türkân Akyol'dur (1971)." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Fransa'da 5. Cumhuriyet, 1958'de Charles de Gaulle tarafından kurulmuştur." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Nelson Mandela, Nobel Barış Ödülü kazanmıştır (1993)." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Türkiye'de 1961 Anayasası halkoyuyla kabul edilen ilk anayasadır." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Ronald Reagan, 1981'de suikast girişiminden yaralı olarak kurtulmuştur." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Türkiye'de ilk kadın milletvekilleri 1935 seçimlerinde Meclis'e girmiştir." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "SSCB, 1922'de kurulmuş ve 1991'de dağılmıştır (69 yıl)." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Yaser Arafat, 1994'te Nobel Barış Ödülü almıştır." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Türkiye'de 12 Eylül 1980 darbesi öncesinde 24 saat içinde 20 kişi öldürülüyordu." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "ABD'nin ilk kadın başkan yardımcısı Kamala Harris'tir (2021)." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Hindistan, 1947'de İngiltere'den bağımsızlığını kazanmıştır." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Türkiye, 1946'da çok partili hayata geçmiştir." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Nelson Mandela, 1994'te Güney Afrika'nın ilk siyahi başkanı seçilmiştir." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Adolf Hitler, 1933'te Almanya Şansölyesi olmuştur." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "İsmet İnönü, 1938-1950 arası Cumhurbaşkanlığı yapmıştır." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Türkiye'nin ilk kadın valisi Lale Aytaman 1991'de Muğla'ya atanmıştır." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Kaddafi, 42 yıl boyunca Libya'yı yönetmiştir." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Türkiye'de ilk koalisyon hükümeti 1961'de CHP-AP arasında kurulmuştur." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "II. Dünya Savaşı sonrası Avrupa'da komünist rejimler kurulmuştur." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Avrupa Birliği'nin resmi para birimi Euro, 2002'de tedavüle girmiştir." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Türkiye, 1952'de NATO'ya üye olmuştur." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Saddam Hüseyin, 2006'da idam edilmiştir." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Türkiye'nin ilk kadın bakanı Türkân Akyol'dur (1971, Sağlık Bakanı)." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Japonya, 1947'de kadınlara seçme ve seçilme hakkı vermiştir." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "II. Dünya Savaşı sonrası Almanya ikiye bölünmüş, 1990'da birleşmiştir." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Türkiye'de 1960 darbesi sonrası ilk kez Anayasa Mahkemesi kurulmuştur." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Fransa'nın ilk kadın başbakanı Édith Cresson'dur (1991)." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Türkiye, 1987'de AB'ye tam üyelik başvurusu yapmıştır." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "SSCB'de ilk ve son başkan Mihail Gorbaçov'dur." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Türkiye'de 1980 darbesi öncesi 5.000'den fazla kişi siyasi cinayetlerde ölmüştür." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Winston Churchill, 1940-1945 ve 1951-1955 arası iki dönem başbakanlık yapmıştır." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Türkiye'nin 11. Cumhurbaşkanı Abdullah Gül'dür (2007-2014)." },
  { "kategori": "siyaset", "ikon": "🏛️", "bilgi": "Almanya'nın ilk kadın şansölyesi Angela Merkel'dir (2005-2021)." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "Neil Armstrong'un uzay kıyafeti, Türk işçileri tarafından dikilmiştir." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "İlk bilgisayar ENIAC, 1945'te icat edilmiş ve 27 ton ağırlığındaydı." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "İnternet, 1969'da ABD Savunma Bakanlığı projesi ARPANET ile doğmuştur." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "İlk cep telefonu 1973'te Martin Cooper tarafından icat edilmiştir ve 1 kg ağırlığındaydı." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "SSCB, 1957'de Sputnik 1'i uzaya göndererek Uzay Yarışı'nı başlatmıştır." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "İlk başarılı kalp nakli 1967'de Güney Afrika'da yapılmıştır." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "Kuduz aşısını ilk kez Louis Pasteur 1885'te geliştirmiştir." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "İlk nükleer reaktör 1942'de Chicago'da çalıştırılmıştır." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "DNA'nın çift sarmal yapısı 1953'te Watson ve Crick tarafından keşfedilmiştir." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "İlk yapay uydu Sputnik, 1957'de SSCB tarafından fırlatılmıştır." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "Ay'a ilk ayak basan insan Neil Armstrong'dur (20 Temmuz 1969)." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "İlk Türk uydusu Türksat 1B, 1994'te uzaya gönderilmiştir." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "Cep telefonuyla ilk görüntülü görüşme 1993'te yapılmıştır." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "İnsanlık tarihinin ilk web sitesi 1991'de Tim Berners-Lee tarafından yayına alınmıştır." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "İlk başarılı organ nakli 1954'te böbrek üzerinde yapılmıştır." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "Yapay zeka terimi ilk kez 1956'da Dartmouth Konferansı'nda kullanılmıştır." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "İlk GPS uydusu 1978'de ABD tarafından fırlatılmıştır." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "Penisilin, 1928'de Alexander Fleming tarafından keşfedilmiştir." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "Bugün internete bağlı cihaz sayısı 20 milyarı aşmıştır." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "İlk siyah-beyaz televizyon yayını 1928'de yapılmıştır." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "CERN'deki Büyük Hadron Çarpıştırıcısı dünyanın en büyük makinesidir." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "İlk yapay kalp 1982'de bir insana nakledilmiştir." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "Kuantum bilgisayarlar, klasik bilgisayarlardan milyonlarca kat hızlıdır." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "İlk renkli televizyon yayını 1951'de ABD'de yapılmıştır." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "Türkiye'nin ilk yerli otomobili Devrim, 1961'de üretilmiştir." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "İnternet üzerinden ilk e-posta 1971'de gönderilmiştir." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "İlk dijital fotoğraf makinesi 1975'te Kodak tarafından geliştirilmiştir." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "Uzayda ilk Türk astronot Alper Gezeravcı'dır (2024)." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "İlk uçak 1903'te Wright Kardeşler tarafından uçurulmuştur." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "Bugün kullanılan ilk web tarayıcısı 1993'te geliştirilmiştir." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "İlk yapay zeka programı 1956'da yazılmıştır." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "Türkiye'nin ilk yerli uçağı Vecihi K-VI, 1924'te yapılmıştır." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "Uzay istasyonu ISS, 1998'den beri yörüngededir." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "İlk başarılı DNA parmak izi testi 1984'te yapılmıştır." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "Dünyanın ilk tüp bebeği Louise Brown, 1978'de doğmuştur." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "İlk jet uçağı 1939'da Almanya'da uçurulmuştur." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "İlk MR cihazı 1977'de kullanılmıştır." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "Yapay zeka, 2016'da Go oyununda dünya şampiyonunu yenmiştir." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "Türkiye'nin ilk yerli otomobili TOGG, 2023'te yollara çıkmıştır." },
  { "kategori": "bilim", "ikon": "🔬", "bilgi": "İlk lazer 1960'ta icat edilmiştir." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Türkiye'nin ilk kadın tiyatro sanatçısı Afife Jale'dir." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "İstanbul, dünyada iki kıtaya yayılan tek megakenttir." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Nobel Edebiyat Ödülü kazanan ilk Türk, Orhan Pamuk'tur (2006)." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "İlk Türkçe gazete, 1831'de Takvim-i Vekayi adıyla yayımlanmıştır." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Dünyanın en eski yerleşim yeri Göbeklitepe'dir ve Türkiye'dedir." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "İlk Türk kadın sinema oyuncusu Bedia Muvahhit'tir." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "İstiklal Marşı, 1921'de Mehmet Akif Ersoy tarafından yazılmıştır." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Ayasofya, 1934'te müze olmuş, 2020'de yeniden cami olmuştur." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Türkiye'nin ilk kadın gazetecisi Fatma Aliye Topuz'dur." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Karagöz ve Hacivat, UNESCO Somut Olmayan Kültürel Miras listesindedir." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Türkiye'nin ilk kadın romancısı Fatma Aliye Topuz'dur." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "İlk Türk opera eseri 'Özsoy', 1934'te sahnelenmiştir." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Dünyanın ilk üniversitesi kabul edilen Nizamiye Medreseleri, 1065'te kurulmuştur." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "İlk Türk kadın ressam Mihri Rasim'dir." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Türkiye'nin ilk kadın heykeltıraşı Sabiha Bengütaş'tır." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "İlk Türkçe roman 'Taaşşuk-ı Talat ve Fitnat', 1872'de yazılmıştır." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Dünyanın ilk yazılı destanı Gılgamış Destanı'dır." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Türkiye'nin ilk kadın bestecisi Leyla Saz'dır." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "İlk Türk kadın fotoğrafçı Naciye Suman'dır." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Yunus Emre'nin şiirleri 700 yıldır okunmaktadır." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Türkiye'nin ilk kadın müzisyeni Dilhayat Kalfa'dır." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Mevlana'nın Mesnevi'si 25.000 beyitten oluşur." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "İlk Türkçe sözlük Kaşgarlı Mahmud'un Divanü Lugati't-Türk'üdür." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Türk kahvesi, UNESCO Somut Olmayan Kültürel Miras listesindedir." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Türkiye'nin ilk kadın mimarı Mualla Eyüboğlu'dur." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "İlk Türkçe Kur'an tercümesi 1914'te yapılmıştır." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Aşık Veysel, görme yetisini 7 yaşında kaybetmiştir." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "İlk Türk kadın avukat Süreyya Ağaoğlu'dur." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Nasreddin Hoca fıkraları 13. yüzyıldan beri anlatılmaktadır." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "İlk Türk kadın doktor Safiye Ali'dir." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Türkiye'nin ilk kadın hakimi Beyhan Hanım'dır." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Dede Korkut Hikayeleri, UNESCO listesindedir." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "İlk Türk kadın pilot Sabiha Gökçen'dir." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Türkiye'nin ilk kadın öğretmeni Refet Angın'dır." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Keloğlan masalları yüzyıllardır anlatılmaktadır." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "İlk Türk kadın milletvekilleri 1935 seçimlerinde seçilmiştir." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Türkiye'nin ilk kadın gazetesi 'Terakki-i Muhadderat'tır." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "İstanbul, 2010'da Avrupa Kültür Başkenti olmuştur." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Türkiye'nin ilk kadın mimarı Mualla Eyüboğlu, Hasankeyf restorasyonunda çalışmıştır." },
  { "kategori": "kultur", "ikon": "🎭", "bilgi": "Mimar Sinan, hayatı boyunca 300'den fazla eser inşa etmiştir." }
];
